config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from explorea.events import views


urlpatterns = [
    #path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('events/', include('explorea.events.urls',namespace='events')),
    path('accounts/', include('explorea.accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('cart/', include('explorea.cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

explorea/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name='accounts'

urlpatterns = [
    
    #path('profile/', views.profile, name='profile'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('login/', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/events/search/all/'}, name='logout'),
    #path('register/', views.register, name='register'),
    path('register/', views.RegisterView.as_view(), name='register'),
    #path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/edit/', views.EditProfileView.as_view(), name='edit_profile'),
    #path('change-password/', views.change_password, name='change_password'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('reset-password/', auth_views.password_reset, 
        {'template_name': 'accounts/reset_password.html', 
        'post_reset_redirect':'password_reset_done','email_template_name':'accounts/reset_password_email.html'}, 
        name='reset_password'),
    path('reset-password/done/', auth_views.password_reset_done,  name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, 
        {'post_reset_redirect':'password_reset_complete'}, name='password_reset_confirm'),
    path('reset-password/complete/', auth_views.password_reset_complete, name='password_reset_complete'),
    #path('hosts/', views.host_list, name='host_list'),
    path('hosts/', views.HostListView.as_view(), name='host_list'),
    #path('become-host/', views.become_host, name='become_host'),
    path('become-host/', views.BecomeHostView.as_view(), name='become_host'),
    #url(r'^become-host/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.activate_host,name='activate_host'),    
    url(r'^become-host/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.ActivateHost.as_view(),name='activate_host'),    
    #path('host/profile/<username>/', views.host_profile, name='host_profile'),
    path('host/profile/<username>/', views.HostProfileView.as_view(), name='host_profile'),
    
]

explorea/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='detail'),
    path('add/<slug:event_slug>/', views.CartAddView.as_view(), name='add'),
    path('remove/<int:product_id>/', views.RemoveCartView.as_view(), name='remove'),
]

explorea/events/urls.py
from django.urls import path

from . import views

app_name='events'

urlpatterns = [
    
    
    #path('', views.event_listing, name='events'),
    
    #path('new/', views.create_event, name='create_event'),
    path('new/', views.CreateEventView.as_view(), name='create_event'),
    #path('my_events/', views.my_events, name='my events'),
    path('my_events/', views.MyEventsView.as_view(), name='my_events'),
    #path('search/', views.event_search, name='search'),
    path('search/<category>/', views.EventListAndSearchView.as_view(), name='search'),

    #path('events/detail/<slug:slug>/', views.event_detail, name='detail'),
    path('events/detail/<slug:slug>/', views.EventDetailView.as_view(), name='detail'),
    #path('events/edit/<slug:slug>/', views.edit_event, name='edit_event'),
    path('events/edit/<slug:slug>/', views.UpdateEventView.as_view(), name='edit_event'),
    
    #path('events/delete/<slug:slug>/', views.delete_event, name='delete_event'),
    path('events/delete/<slug:slug>/', views.DeleteEventView.as_view(), name='delete_event'),
    

    path('events_run/', views.events_run_listing, name='events_run'),
    #path('events_run/new/<slug:slug>', views.new_event_run, name='new_event_run'),
    path('events_run/new/<slug:slug>', views.CreateEventRunView.as_view(), name='new_event_run'),
    #path('events_run/edit/<int:event_run_id>', views.edit_event_run, name='edit_event_run'),
    path('events_run/edit/<int:event_run_id>', views.UpdateEventRunView.as_view(), name='edit_event_run'),
    #path('events_run/delete/<int:event_run_id>', views.delete_event_run, name='delete_event_run'),
    path('events_run/delete/<int:pk>', views.DeleteEventRunView.as_view(), name='delete_event_run'),

    #path('<category>/', views.event_listing, name='events'),
    #path('<category>/', views.EventListView.as_view(), name='events'),

    
]

explorea/accounts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

def image_dir(instance, filename):
    return 'user_{}/profile_{}'.format(instance.user.id, filename)

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE, primary_key=True)
    is_host = models.BooleanField(default=False)
    about = models.TextField(max_length=500)
    avatar = models.ImageField('Upload your photo', 
        upload_to=image_dir, null=True)

    def get_absolute_url(self):
        return reverse('accounts:host_profile', args=[self.user.username])

explorea/cart/models.py
from django.db import models

# Create your models here.

explorea/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import Profile

from core.validators import validate_human_name

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    last_name = forms.CharField(max_length=100, validators=[validate_human_name,])

    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        ]

class EditUserForm(UserChangeForm):
    first_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    last_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        ]

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['about','avatar']

explorea/cart/forms.py
from explorea.events.models import Event, EventRun
from django import forms


class PositiveIntegerField(forms.IntegerField):

    def validate(self, value):
        super().validate(value)
        if value < 1:
            raise forms.ValidationError('Only positive integer allowed')

class CartAddForm(forms.Form):
    quantity = PositiveIntegerField(initial=0)
    product_id = forms.CharField(max_length=10, widget=forms.HiddenInput())
    max_seats = forms.IntegerField(required=False, initial=0, widget=forms.HiddenInput)
                                   

    def clean(self):
            
            super().clean()
            
            product_id = self.cleaned_data.get("product_id")
            quantity = self.cleaned_data.get("quantity")
            max_seats = self.cleaned_data.get("max_seats")
            
            if quantity is not None and max_seats is not None:
                if quantity > max_seats:
                        msg="It is not enough seats available"
                        self.add_error('quantity', msg)
                        print(self.has_error('quantity'))
                        
                        
                
            

explorea/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, authenticate, login,update_session_auth_hash
from .forms import RegisterForm, EditUserForm, EditProfileForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
import pdb

from django.views.generic import ListView, DetailView,TemplateView
from django.views.generic.edit import DeleteView, CreateView, UpdateView, FormView, FormMixin

#class views mixins
from django.contrib.auth.mixins import LoginRequiredMixin
#from django.contrib.auth import get_user_model


token_generator = PasswordResetTokenGenerator()
UserModel = get_user_model()



# Create your views here.

class ProfileView(TemplateView):
    template_name = 'accounts/profile.html'


class RegisterView(CreateView):
    model = UserModel
    form_class = RegisterForm
    template_name = 'accounts/register.html'

    def form_valid(self, form):
        user=form.save()

        raw_password = form.cleaned_data.get('password1')  

        user = authenticate(username=user.username, password=raw_password)
        login(self.request, user)

        return redirect('accounts:profile')

# class EditProfileView(LoginRequiredMixin, FormView):
#     template_name ='accounts/edit_profile.html'
#     success_url = reverse_lazy('accounts:profile')
    
#     def get(self, request, *args, **kwargs):
#         user_form = EditUserForm(request.POST or None, instance=request.user)
#         profile_form = EditProfileForm(request.POST or None, request.FILES or None, instance=request.user.profile)

#         kwargs={'user_form': user_form,'profile_form': profile_form }
#         return self.render_to_response(self.get_context_data(**kwargs))

#     def get_context_data(self, **kwargs):
#         return kwargs    
    
#     def post(self, request, *args, **kwargs):
#         user_form = EditUserForm(request.POST or None, instance=request.user)
#         profile_form = EditProfileForm(request.POST or None, request.FILES or None, instance=request.user.profile)

#         if user_form.is_valid() and profile_form.is_valid():
#             user = user_form.save()
#             profile = profile_form.save()
#             return HttpResponseRedirect(self.get_success_url())
#         else:
#             kwargs={'user_form': user_form,'profile_form': profile_form }
#             return self.render_to_response(self.get_context_data(**kwargs))

class EditProfileView(LoginRequiredMixin, FormView):
    template_name ='accounts/edit_profile.html'
    success_url = reverse_lazy('accounts:profile')
    user_form=None
    profile_form=None
    
    def dispatch(self, request, *args, **kwargs):
        self.user_form = EditUserForm(request.POST or None, 
                                instance=request.user)
        self.profile_form = EditProfileForm(request.POST or None, 
                                        request.FILES or None, 
                                        instance=request.user.profile)
        self.form_context = {'user_form': self.user_form,'profile_form': self.profile_form }

        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return self.render_to_response(self.form_context)
 
    
    def post(self, request, *args, **kwargs):
        if self.user_form.is_valid() and self.profile_form.is_valid():
            user = self.user_form.save()
            profile = self.profile_form.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.form_context)
            


class ChangePasswordView(LoginRequiredMixin, UpdateView):
    model = UserModel
    form_class = PasswordChangeForm
    template_name = 'accounts/change_password.html'
    success_url = reverse_lazy('accounts:profile')

    def form_valid(self, form):
        self.object = form.save()
        update_session_auth_hash(self.request, self.object)
        return HttpResponseRedirect(self.get_success_url())

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.pop('instance')
        kwargs.update({'user': self.object})
        return kwargs

    
    def get_object(self):
        return self.request.user

class HostListView(LoginRequiredMixin,ListView):
    context_object_name = 'profiles'
    template_name = 'accounts/host_list.html'

    def get_queryset(self):
        profiles = Profile.objects.filter(is_host=True)
        if self.request.user.profile.is_host:
            profiles = profiles.exclude(user__pk=self.request.user.id)
        return profiles


class BecomeHostView(LoginRequiredMixin,TemplateView):
    template_name = 'accounts/verification_sent.html'

    def get(self, request, *args, **kwargs):
        verification_email_template = 'accounts/host_verification_email.html'
        email_context = {
        'user': request.user,
        'domain': get_current_site(request).domain,
        'uidb64': urlsafe_base64_encode(force_bytes(request.user.pk)).decode(),
        'token': token_generator.make_token(request.user)
        }

        html_body = render_to_string(verification_email_template, email_context)
        subject = 'Explorea Host Verification'
        from_email = 'admin@explorea.com'
        to_email = request.user.email
        
        email = EmailMessage(subject, html_body, from_email, [to_email])
        email.send()

        return super().get(self, request,*args,**kwargs)



# def activate_host(request, uidb64, token):
#     try:
#         uid = urlsafe_base64_decode(uidb64).decode()
#         user = UserModel._default_manager.get(pk=uid)
#     except (TypeError, ValueError, OverflowError, User.DoesNotExist):
#         user = None

#     if user is not None and token_generator.check_token(user, token):
#         user.profile.is_host = True
#         user.profile.save()
#         return render(request, 'accounts/verification_complete.html')

#     else:
#         return render(request, 'accounts/invalid_link.html')

class ActivateHost(TemplateView):
    def get(self, request, *args, **kwargs):
        uidb64=self.kwargs['uidb64']
        token=self.kwargs['token']
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = UserModel._default_manager.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and token_generator.check_token(user, token):
            user.profile.is_host = True
            user.profile.save()
            self.template_name = 'accounts/verification_complete.html'

        else:
            self.template_name = 'accounts/invalid_link.html'
        
        return super().get(self, request,*args,**kwargs)

class HostProfileView(LoginRequiredMixin,DetailView):
    model = UserModel
    context_object_name = 'host'
    template_name = 'accounts/host_profile.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'


    

explorea/cart/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.contrib import messages

from explorea.events.models import Event, EventRun
from .forms import CartAddForm
from .cart import Cart

class CartDetailView(TemplateView):
    template_name = "cart/cart_detail.html"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     cart = Cart(self.request.session)
    #     if cart.is_empty():
    #         context = None
    #     else:
    #         context['cart'] = cart
    #     return context
        
        

class CartAddView(SingleObjectMixin, FormView):
    model = Event
    form_class =  CartAddForm
    template_name = 'events/event_detail.html'
    slug_url_kwarg = 'event_slug'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return self.object.get_absolute_url()

    def form_valid(self, form):
        cart = Cart(self.request.session)
        cart.add(**form.cleaned_data)
        messages.success(self.request, 'The run has been added to the cart')
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        messages.error(self.request, 'The run could not be added into the cart')
        return HttpResponseRedirect(self.get_success_url())


class RemoveCartView(TemplateView):
    template_name = "cart/cart_detail.html"
    pk_url_kwarg = 'product_id'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = Cart(self.request.session)
        cart.remove(kwargs['product_id'])
        if cart.is_empty():
            context = None
        else:
            context['cart'] = cart
        return context

explorea/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}

<form method='POST'>

    {% csrf_token %}

    {% for field in form.visible_fields %}
        
        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        <p>{{ field.label_tag}}{{ field }}</p>

    {% endfor %}
    <input type="submit" value="Change">
    
</form>

{% endblock content %}

explorea/templates/accounts/edit_profile.html
{% extends 'base.html' %} 

{% block title %}
<title>Profile</title>
{% endblock title %}

{% block content %}
<div class="basic-form-margin">

  <h2>Edit your profile</h2>
  
  <form class="form-style" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in user_form.visible_fields %}
     
      {% if  field.label != "Password" %}
        {% for error in field.errors %}
        {{ error }}
        {% endfor %} 

        <p>{{ field.label_tag}}{{ field }}</p>
      {% endif %}
      
    {% endfor %}

    {% for field in profile_form.visible_fields %}
     
      
        {% for error in field.errors %}
        {{ error }}
        {% endfor %} 

        <p>{{ field.label_tag}}{{ field }}</p>
            
    {% endfor %}
    
    <button type="submit">Save</button>
  </form>
  
</div>
{% endblock content %}

explorea/templates/accounts/host_list.html
{% extends 'base.html' %}
{% load account_tags %}
{% load static%}

{% block title %}
<title>Email sent</title>
{% endblock title %}

{% block content %}
<a href="{% url 'accounts:become_host' %}">Become a host</a>

<div class="host-container">
{% for profile in profiles %}
    <div class="hosts-tile">
        <a  href="{{ profile.get_absolute_url }}">
            {% if  profile.avatar|has:'url' %}
                <img src="{{ profile.avatar.url }}" alt='{{ profile.user.username }}'>
            {% else %}
                <img src="{% static 'img/avatar.jpg' %}" alt='Not Available'>
            {% endif %}

            <p>{{ profile.user.username }}</p>
        </a>
    </div>

{% endfor %}
</div>

{% endblock content %}

explorea/templates/accounts/host_profile.html
{% extends 'base.html' %}
{% load static %}
{% load account_tags %}

{% block content %}

<br>
<table>
    <tr>
        <td>
        {% if  host.profile.avatar|has:'url' %}
            <img src="{{ host.profile.avatar.url }}">
        {% else %}
            <img src="{% static 'img/avatar.png' %}">
        {% endif %}
        </td>

    </tr>
    <tr>
        <td>hostname: </td><td>{{ host.hostname }}</td>
    </tr>
    <tr>
        <td>First Name: </td><td>{{ host.first_name }}</td>
    </tr>
    <tr>
        <td>Last Name: </td><td>{{ host.last_name }}</td>
    </tr>
    <tr>
        <td>Email: </td><td>{{ host.email }}</td>
    </tr>
    <tr>
        <td>Joined: </td><td>{{ host.date_joined }}</td>
    </tr>
    <tr>
        <td>About Me: </td><td>{{ host.profile.about }}</td>
    </tr>
</table>

{% endblock content %}

explorea/templates/accounts/host_verification_email.html
<p>Dear {{ user.username }}</p>

<p>You are one step from becoming host at Explorea. Please click the below link button to complete the verification:</p>

<a href="http://{{ domain }}{% url 'accounts:activate_host' uidb64 token %}" target="_blank">Verify</a>


<p>Thanks for using our site!</p>

<p>The Explorea team</p>

explorea/templates/accounts/invalid_link.html
{% extends 'base.html' %}

{% block title %}
<title>Link invalid</title>
{% endblock title %}

{% block content %}
<p>Unfortunately we were not able to perform the verification. Is it possible that your link is older than 7 days?</p>

<p><a href="{% url 'accounts:become_host' %}">Apply again</a></p>
{% endblock content %}

explorea/templates/accounts/logged_out.html
{% extends 'base.html' %}

{% block content %}
<h2>Ciao</h2>

<p>You have been logged out. But if you decide to log in again, we will be happy to see you here.</p>

{% endblock content %}

explorea/templates/accounts/login.html
{% extends 'base.html' %} 

{% block title %}<title>Login</title>{% endblock title %}

{% block content %}

<div class="basic-form-margin">
  <h2>Login</h2>
  
  <form class="form-style" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
  
</div>

{% endblock %}

explorea/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load account_tags %}

{% block content %}
<div class="profile-container">
<td>
    {% if user.profile.avatar|has:'url' %}
        <img src="{{ user.profile.avatar.url }}">
    {% else %}
        <img src="{% static 'img/avatar.jpg' %}">
    {% endif %}
</td>
<br>
<div class="profile-data">
        <p class="item-name">Username: </p><p>{{ user.username }}</p>
        <p class="item-name">First Name: </p><p>{{ user.first_name }}</p>
        <p class="item-name">Last Name: </p><p>{{ user.last_name }}</p>
        <p class="item-name">Email: </p><p>{{ user.email }}</p>
        <p class="item-name">Joined: </p><p>{{ user.date_joined }}</p>
   
</div>

</div>
<br>

<div class="profile-links">
{% if user.is_authenticated %}
<a href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
<a href="{% url 'accounts:change_password' %}">Change Password</a>
{% endif %}
</div>

{% endblock content %}

explorea/templates/accounts/register.html
{% extends 'base.html' %} 

{% block title %}
<title>Register</title>
{% endblock title %}

{% block content %}
<div class="basic-form-margin">

  <h2>Register</h2>
 
  
  <form class="form-style" method="post">
    {% csrf_token %}
    {% for field in form.visible_fields %}
        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        <p>{{ field.label_tag}}{{ field }}</p>

    {% endfor %}
    <button type="submit">Save</button>
  </form>
  
</div>
{% endblock content %}

explorea/templates/accounts/reset_password.html
{% extends 'base.html' %} 

{% block title %}
<title>Password Reset</title>
{% endblock title %}

{% block content %}
<div>

  <h2>Password Reset</h2>
  <p>Enter your email below and click "Submit". We will send you the reset link to your email immediately.</p>
  
  <form method="post">
    {% csrf_token %}

    {% for field in form.visible_fields %}
        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        <p>{{ field.label_tag}} {{ field }}</p>

    {% endfor %}
    
    <button type="submit">Save</button>
  </form>
  
</div>
{% endblock content %}

explorea/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

explorea/templates/accounts/verification_complete.html
{% extends 'base.html' %}

{% block title %}
<title>Link invalid</title>
{% endblock title %}

{% block content %}
<p>Congratulations, you can now begin to earn your money.</p>

<p><a href="{% url 'events:create_event' %}"><strong>Create your first event</strong></a></p>
{% endblock content %}

explorea/templates/accounts/verification_sent.html
{% extends 'base.html' %}

{% block title %}
<title>Email sent</title>
{% endblock title %}

{% block content %}
<p>Time to check your email. We have sent you and email to <strong>{{ request.user.email }}</strong> with verification link. Please, click it and we are done</p>

<p>You can close this tab if your want</p>
{% endblock content %}