config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from explorea.events import views


urlpatterns = [
    #path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    path('events/', include('explorea.events.urls',namespace='events')),
    path('accounts/', include('explorea.accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('cart/', include('explorea.cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

explorea/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name='accounts'

urlpatterns = [
    
    #path('profile/', views.profile, name='profile'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('login/', auth_views.login, {'template_name': 'accounts/login.html'}, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/events/search/all/'}, name='logout'),
    #path('register/', views.register, name='register'),
    path('register/', views.RegisterView.as_view(), name='register'),
    #path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/edit/', views.EditProfileView.as_view(), name='edit_profile'),
    #path('change-password/', views.change_password, name='change_password'),
    path('change-password/', views.ChangePasswordView.as_view(), name='change_password'),
    path('reset-password/', auth_views.password_reset, 
        {'template_name': 'accounts/reset_password.html', 
        'post_reset_redirect':'password_reset_done','email_template_name':'accounts/reset_password_email.html'}, 
        name='reset_password'),
    path('reset-password/done/', auth_views.password_reset_done,  name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, 
        {'post_reset_redirect':'password_reset_complete'}, name='password_reset_confirm'),
    path('reset-password/complete/', auth_views.password_reset_complete, name='password_reset_complete'),
    #path('hosts/', views.host_list, name='host_list'),
    path('hosts/', views.HostListView.as_view(), name='host_list'),
    #path('become-host/', views.become_host, name='become_host'),
    path('become-host/', views.BecomeHostView.as_view(), name='become_host'),
    #url(r'^become-host/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.activate_host,name='activate_host'),    
    url(r'^become-host/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.ActivateHost.as_view(),name='activate_host'),    
    #path('host/profile/<username>/', views.host_profile, name='host_profile'),
    path('host/profile/<username>/', views.HostProfileView.as_view(), name='host_profile'),
    
]

explorea/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetailView.as_view(), name='detail'),
    path('add/<slug:event_slug>/', views.CartAddView.as_view(), name='add'),
    path('remove/<int:product_id>/', views.RemoveCartView.as_view(), name='remove'),
]

explorea/events/urls.py
from django.urls import path

from . import views

app_name='events'

urlpatterns = [
    
    
    #path('', views.event_listing, name='events'),
    
    #path('new/', views.create_event, name='create_event'),
    path('new/', views.CreateEventView.as_view(), name='create_event'),
    #path('my_events/', views.my_events, name='my events'),
    path('my_events/', views.MyEventsView.as_view(), name='my_events'),
    #path('search/', views.event_search, name='search'),
    path('search/<category>/', views.EventListAndSearchView.as_view(), name='search'),

    #path('events/detail/<slug:slug>/', views.event_detail, name='detail'),
    path('events/detail/<slug:slug>/', views.EventDetailView.as_view(), name='detail'),
    #path('events/edit/<slug:slug>/', views.edit_event, name='edit_event'),
    path('events/edit/<slug:slug>/', views.UpdateEventView.as_view(), name='edit_event'),
    
    #path('events/delete/<slug:slug>/', views.delete_event, name='delete_event'),
    path('events/delete/<slug:slug>/', views.DeleteEventView.as_view(), name='delete_event'),
    

    path('events_run/', views.events_run_listing, name='events_run'),
    #path('events_run/new/<slug:slug>', views.new_event_run, name='new_event_run'),
    path('events_run/new/<slug:slug>', views.CreateEventRunView.as_view(), name='new_event_run'),
    #path('events_run/edit/<int:event_run_id>', views.edit_event_run, name='edit_event_run'),
    path('events_run/edit/<int:event_run_id>', views.UpdateEventRunView.as_view(), name='edit_event_run'),
    #path('events_run/delete/<int:event_run_id>', views.delete_event_run, name='delete_event_run'),
    path('events_run/delete/<int:pk>', views.DeleteEventRunView.as_view(), name='delete_event_run'),

    #path('<category>/', views.event_listing, name='events'),
    #path('<category>/', views.EventListView.as_view(), name='events'),

    
]

explorea/cart/models.py
from django.db import models

# Create your models here.

explorea/events/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import date
from django.db.models import Max, F, Q
from django.utils.text import slugify
from django.urls import reverse

from _operator import attrgetter

from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

def thumbnail_image_url(instance, filename):
    '''upload_to for Event thumbnail image'''
    return 'user_{0}/thumb_{1}'.format(instance.host.id, filename) 


def main_image_url(instance, filename):
    '''upload_to for Event main image'''
    return 'user_{0}/main_{1}'.format(instance.host.id, filename)

def album_image_url(instance, filename):
    '''upload_to for Image model'''
    return 'user_{0}/{1}/{2}'.format(instance.album.event.host.id, 
        instance.album.title, filename)

class EventQuerySet(models.QuerySet):

    def filter_by_category(self, category):
        db_equivalent = ''
        for pair in Event.CATEGORY_CHOICES:
            if pair[1] == category:
                db_equivalent = pair[0]
                break
        else:
            return self.all()

        return self.filter(category=db_equivalent)

        
    def filter_available(self, date_from=None, date_to=None, guests=None):
        # filter first all the eventruns and then get the ids to events     
        date_from = date_from or timezone.now().date()
        
        if date_to:
            qs = EventRun.objects.filter(date__range=(date_from, date_to))
        else:
            qs = EventRun.objects.filter(date__gte=date_from)

        if guests:
            qs = qs.filter(seats_available__gte=guests)
        # value_list() creates a list of tuples containing values from objects in qs. Argument 'events' 
        # tell that only values from event column will be listed, flat means that the final list will not be nested list.
        return self.filter(pk__in=[qs.values_list('event', flat=True)])
    
       
class EventRunQuerySet(models.QuerySet):
    def filter_by_category(self, category=None):
        db_equivalent = ''
        for pair in Event.CATEGORY_CHOICES:
            if pair[1] == category:
                db_equivalent = pair[0]
                break
        else:
            return self.all()

        return self.filter(event__category=db_equivalent)

    def filter_available(self, date_from=None, date_to=None, guests=None):
        # filter first all the eventruns and then get the ids to events     
        date_from = date_from or timezone.now().date()
            
        if date_to:
            qs = self.filter(date__range=(date_from, date_to))
        else:
            qs = self.filter(date__gte=date_from)

        if guests:
            qs = qs.filter(seats_available__gte=guests)
            
        return qs

    def filter_first_available(self, date_from=None, date_to=None, guests=None,order_by='date'):
        qs=self.filter_available(date_from, date_to, guests).order_by('date','time')

            #list of events corresponding to next eventruns
        event_ids=[]

            #list of earliest eventruns grouped by events
        filtered_eventruns=[]

        for run in qs:
            if not run.event.id in event_ids:
                filtered_eventruns.append(run)
                event_ids.append(run.event.id)
        
        reverse = False
        # if this condition is not added, than in the case with no filter, pagination somehow modified the order_by
        # argument on empty string and error occures
        if not order_by:
            order_by='date'

        if order_by[0]=='-':
            reverse=True
            order_by=order_by.lstrip('-')

        ordered_result=sorted(filtered_eventruns,key=attrgetter(order_by),reverse=reverse)
        #ordered_result=sorted(filtered_eventruns,key=lambda x:f(x))
        return ordered_result



    

class EventManager(models.Manager):
    def get_queryset(self):
        return EventQuerySet(self.model, using=self._db)

    # def search(self, query=None):
    #     lookup = (
    #         Q(event__name__icontains=query) |
    #         Q(event__description__icontains=query) |
    #         Q(event__location__icontains=query)
    #     )
    #     return self.filter(lookup).distinct()

class EventRunManager(models.Manager):
    
    def get_queryset(self):
        return EventRunQuerySet(self.model, using=self._db)

    def search(self, query=None):
        lookup = (
            Q(event__name__icontains=query) |
            Q(event__description__icontains=query) |
            Q(event__location__icontains=query)
        )
        return self.filter(lookup).distinct()

    
# Create your models here.
class Event(models.Model):

    FUN = 'FN'
    RELAX = 'RX'
    EXP = 'EX'
    SIGHTS = 'SI'

    CATEGORY_CHOICES= (
        (FUN, 'fun'),
        (RELAX, 'relax'),
        (EXP, 'experience'),
        (SIGHTS, 'sights')
    )

    host = models.ForeignKey(settings.AUTH_USER_MODEL, 
          on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1000)
    location = models.CharField(max_length=500)
    category = models.CharField(
        max_length=20,
        choices = CATEGORY_CHOICES,
        default = FUN,
    )
    slug = models.SlugField(max_length=200, unique=True,null=True)
    created = models.DateTimeField(auto_now_add=True,null=True)
    thumbnail = ProcessedImageField(upload_to=thumbnail_image_url,
        processors=[ResizeToFill(300,200)],
        format='PNG',
        options={'quality':60},
        null=True,
        blank=True)
    main_image = ProcessedImageField(upload_to=main_image_url,
        processors=[ResizeToFill(500,600)],
        format='PNG',
        options={'quality':100},
        null=True,
        blank=True)


    objects=EventManager()

    def __str__(self):
        return self.name

    def active_runs(self):
        today = timezone.now().date()
        return self.eventrun_set.filter(date__gte=today)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name + '-with-' + self.host.username)
        super().save(*args, **kwargs)

        if not hasattr(self, 'album'):
            Album.objects.create(event=self)
    
    def get_absolute_url(self):
        return reverse('events:detail', args=[self.slug])
    
    class Meta:
        ordering = ['name']
        unique_together = (("name", "host"),)
        verbose_name='superevent'


class EventRun(models.Model):

    event = models.ForeignKey(Event, 
        on_delete=models.CASCADE)
    date = models.DateField(blank=False, null=False)
    time = models.TimeField(blank=False, null=False)
    seats_available = models.PositiveIntegerField(blank=False, null=False)
    price = models.DecimalField(max_digits=10, 
        decimal_places=2, blank=False, null=False)
    
    objects=EventRunManager()

    class Meta:
        ordering = ['date','time']

class Album(models.Model):
    event = models.OneToOneField(Event, on_delete=models.CASCADE)
    title = models.CharField(max_length=200, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.title:
            self.title = "album_" + self.event.name
        super().save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.title)

class Image(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    image = ProcessedImageField(upload_to=album_image_url,
            processors=[ResizeToFill(500,400)],
            format='PNG',
            options={'quality':80})
    title = models.CharField(max_length=200, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}/{}'.format(self.album, self.title)


    class Meta:
        ordering = ['created']

explorea/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import Profile

from core.validators import validate_human_name

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    last_name = forms.CharField(max_length=100, validators=[validate_human_name,])

    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        ]

class EditUserForm(UserChangeForm):
    first_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    last_name = forms.CharField(max_length=100, validators=[validate_human_name,])
    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        ]

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['about','avatar']

explorea/cart/forms.py
from explorea.events.models import Event, EventRun
from django import forms


class PositiveIntegerField(forms.IntegerField):

    def validate(self, value):
        super().validate(value)
        if value < 1:
            raise forms.ValidationError('Only positive integer allowed')

class CartAddForm(forms.Form):
    quantity = PositiveIntegerField(initial=0)
    product_id = forms.CharField(max_length=10, widget=forms.HiddenInput())
    max_seats = forms.IntegerField(required=False, initial=0, widget=forms.HiddenInput)
                                   

    def clean(self):
            
            super().clean()
            
            product_id = self.cleaned_data.get("product_id")
            quantity = self.cleaned_data.get("quantity")
            max_seats = self.cleaned_data.get("max_seats")
            
            if quantity is not None and max_seats is not None:
                if quantity > max_seats:
                        msg="It is not enough seats available"
                        self.add_error('quantity', msg)
                        print(self.has_error('quantity'))
                        
                        
                
            

explorea/cart/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.contrib import messages

from explorea.events.models import Event, EventRun
from .forms import CartAddForm
from .cart import Cart

class CartDetailView(TemplateView):
    template_name = "cart/cart_detail.html"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     cart = Cart(self.request.session)
    #     if cart.is_empty():
    #         context = None
    #     else:
    #         context['cart'] = cart
    #     return context
        
        

class CartAddView(SingleObjectMixin, FormView):
    model = Event
    form_class =  CartAddForm
    template_name = 'events/event_detail.html'
    slug_url_kwarg = 'event_slug'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return self.object.get_absolute_url()

    def form_valid(self, form):
        cart = Cart(self.request.session)
        cart.add(**form.cleaned_data)
        messages.success(self.request, 'The run has been added to the cart')
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        messages.error(self.request, 'The run could not be added into the cart')
        return HttpResponseRedirect(self.get_success_url())


class RemoveCartView(TemplateView):
    template_name = "cart/cart_detail.html"
    pk_url_kwarg = 'product_id'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = Cart(self.request.session)
        cart.remove(kwargs['product_id'])
        if cart.is_empty():
            context = None
        else:
            context['cart'] = cart
        return context

explorea/templates/events/create_event.html
{% extends 'base.html' %} 

{% block title %}
<title>New Event</title>
{% endblock title %}

{% block content %}
<div>

  <h2>Edit event {{ event.name }}</h2>
  
  <form class="form-style" method="post" enctype="multipart/form-data">
    <ul class="form-style">
    {% csrf_token %}
    {% for field in form.visible_fields %}
        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        <li>{{ field.label_tag}}{{ field }}

    {% endfor %}

    
    
    <button type="submit">Save</button>
  </ul>
  </form>
  
</div>
{% endblock content %}

explorea/templates/events/edit_event.html
{% extends 'base.html' %} 

{% block title %}
<title>Edit Event</title>
{% endblock title %}

{% block content %}
<div>

  <h2>edit event</h2>
  
  <form method="post">
  <ul class="form-style">
    {% csrf_token %}
    {% for field in form.visible_fields %}
        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        <li>{{ field.label_tag}}{{ field }}

    {% endfor %}
    <button type="submit">Save</button>
  </ul>
  </form>
  
</div>
{% endblock content %}

explorea/templates/events/edit_event_run.html
{% extends 'base.html' %} 

{% block title %}
<title>Edit Event Run</title>
{% endblock title %}

{% block content %}
<div class="basic-form-margin">

  <h2>edit event Run</h2>
  
  <form class="form-style" method="post">
    {% csrf_token %}
    {% for field in form.visible_fields %}
        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        <p>{{ field.label_tag}}{{ field }}</p>

    {% endfor %}
    <button type="submit">Save</button>
  </form>
  
</div>
{% endblock content %}

explorea/templates/events/event_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <button type="submit">Delete</button>
    <a class="button-gold " href="{{ object.get_absolute_url }}">Cancel</a>
</form>

{% endblock %}

explorea/templates/events/event_detail.html
{% extends 'base.html' %}

{% load event_tags %}

{% block title %}
    <title>Event Detail</title>
{% endblock title %}

{% block content %} 
    <div class="event-detail-top">
        <h3 class="event-detail-undertop">DETAIL OF EVENT:{{ events.name }}</h3>
        <!-- {% if run.event.host is user %}
        <a class="event-detail-undertop edit-button" href="{% url 'events:edit_event' events.slug %}">edit event </a>
        <a class="event-detail-undertop edit-button" href="{% url 'events:delete_event' events.slug %}">delete event </a>
        {% endif %} -->
    </div>
        <div class="event-info">
            <div>
                <p> LOCATION: </p>
                <p> DESCRIPTION: </p>
                <p> CATEGORY:  </p>
                <p> HOST:      </p> 
            </div>
            <div>
                <p>{{events.location}}</p>
                <p>{{events.description }} </p>
                <p>{{events.category}}</p>
                <p>{{events.host}} </p> 
            </div>
        </div>
    <div class="event-detail-pictures">
        <div class="main-image">
            {% if events|has:'main_image' %}
            <img src="{{ events.main_image.url }}">
            {% else %}
            <div class="not-available"></div>
            {% endif %}
            
        </div>
        <!--Image slideshow-->
        <div class="owl-carousel">
            {% for image in events.album.image_set.all %}
            <img src="{{ image.image.url }}" alt="{{ image.title }}">
            {% endfor %}
        </div>
    </div>
        

    
    <div class="event-detail-top">
        <h3 class="event-detail-undertop">EVENT RUNS</h3>
        <a class="event-detail-undertop" href="{% url 'events:new_event_run' events.slug %}">ADD EVENT RUN </a>
    </div> 

    <div class="event_run-container">
        <div class="event_run-grid">
            {% if events_run %}
            {% for event_run in events_run %}
            <div class="event_run-detail">
                <p> EVENT:{{event_run.event }} </p>
                <p> DATE: {{ event_run.date}} </p>
                <p> TIME:{{ event_run.time}} </p>
                <p> SEATS AVAILABLE: {{ event_run.seats_available }} </p>
                <p> PRICE:  $ {{event_run.price}} </p> 
                {% if event_run.event.host == user %}
                <a class='edit-button' href="{% url 'events:edit_event_run' event_run.id %}">edit event run </a>
                <a class='edit-button' href="{% url 'events:delete_event_run' event_run.id %}">delete event run</a>
                {% else %}
                <td>
                    <div>
                    <form class='cart-add' method='POST' action="{% url 'cart:add' event_run.event.slug %}">
                        {% csrf_token %}
                        {{ cart_add_form.quantity }}
                        
                        {{ cart_add_form.quantity.errors }}
                        

                        <input name="max_seats" value={{ event_run.seats_available }} type="hidden">   
                        <input name="product_id" value={{ event_run.id }} type="hidden">
                        <button type='submit'>Add to Cart</button>
                    </form>
                    </div>
                </td>
                {% endif %}
                
            </div>
            {% endfor %}
            {% else %}
            <p>No event run for this event</p>
            {% endif %}
            
        </div>
    </div>
    
    {% endblock content %}

explorea/templates/events/event_listing.html
{% extends 'base.html' %}

{% load event_tags %}

{% block title %}
    <title>Event Listing</title>
{% endblock title %}


{% block content %}

    

    <form class="event-filters"  method="GET">
        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}

        {% for field in filter_form.visible_fields %}
            <div class="form-filter">
                {{ field.label_tag }} {{ field }}
                <div class="errors">
                    {% if  field.label == "From" %}
                        {% for error in form.non_field_errors %}
                        <div class="error">XX{{ error }}</div>
                        {% endfor %}
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="error">{{ error }}</div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}          
        
        <button type="submit">Filter</button>
    </form>

    <div class="event-category-filters">
        <!--by clicking these buttons we should be taken to event listing, that show us only events of the given event category-->
        <a class="button-gold" href="{% url 'events:search' 'fun' %}">Fun</a>
        <a class="button-gold" href="{% url 'events:search' 'experience' %}">Experience</a>
        <a class="button-gold" href="{% url 'events:search' 'sights' %}">Sights</a>
        <a class="button-gold" href="{% url 'events:search' 'relax' %}">Relax</a>
        <a class="button-blue" href="{% url 'events:search' 'all' %}">Reset all filters</a>
    </div>
       
    
    <div class="event-container">
        {% if event_runs %}    
        <div class="event-grid">
            {% for eventrun in event_runs %}
            <a class="event-tile" href="{{ eventrun.event.get_absolute_url }}">
                    {% if eventrun.event|has:'thumbnail' %}
                    <img src="{{ eventrun.event.thumbnail.url }}">
                    {% else %}
                    <div class="not-available"></div>
                    {% endif %} 
                    <div class='event-detail'>
                    <p>Host:{{eventrun.event.name}} </p>
                    <p>Name:{{eventrun.event.host }}</p>
                    
                    <p>Next:  {{eventrun.date}}</p> 
                    <p>Price: {{eventrun.price}}</p>
                    <p>Seats: {{eventrun.seats_available}}</p>
                               
                    <p>Price from: ${{ eventrun.event.eventrun_set.all|active|min_attr_value:"price" }}</p>
                    <p>Seats up to: {{ eventrun.event.eventrun_set.all|active|max_attr_value:"seats_available" }}</p>
                    </div>
                    
            </a>                              
            {% endfor %}
        {% else %}
            <div class="info empty-search">No events found ...</div>
        {% endif %}
        </div>  
    </div> 

    {% include 'pagination.html' with page=page_obj %}
    
    
   
{% endblock content %}

explorea/templates/events/eventrun_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <button type="submit">Delete</button>
    <a class="button-gold " href="{% url 'events:my_events' %}">Cancel</a>
</form>

{% endblock %}

explorea/templates/events/events_run_listing.html
<!DOCTYPE html>
<html>
<head>
    <title>Events run Listing</title>
</head>
<body>
    <h3> Events run list</h3>
    <ul>
    {% for event_run in events_run %}
    <li>EVENT:{{ event_run.event }} DATE: {{ event_run.date}} TIME:{{ event_run.time}} SEATS AVAILABLE: {{ event_run.seats_available }} PRICE:{{event_run.price}} <a href='/events_run/edit/{{ event_run.id }}'>edit event run</a> <a href='/events_run/delete/{{ event_run.id }}'>delete event run </a>
    {% endfor %}
    </ul>

</body>
</html>

explorea/templates/events/index.html
{% extends 'base.html' %}

{% block content %}


<div class="main-banner">
        <p class="claim">Quit the daily routine...</p>
        <a class="button-gold" href="{% url 'events:search' 'fun' %}">Fun</a>
        <a class="button-gold" href="{% url 'events:search' 'experience' %}">Experience</a>
        <a class="button-gold" href="{% url 'events:search' 'sights' %}">Sights</a>
        <a class="button-gold" href="{% url 'events:search' 'relax' %}">Relax</a>
    
</div>


{% endblock %}

explorea/templates/events/my_events.html
{% extends 'base.html' %}

{% load event_tags %}


{% block title %}
    <title>My events</title>
{% endblock title %}

{% block content %}

<div class="my-event-container">
<div class="my-event-grid">
    <div class="my-event-tile">
        {% for event in my_events %}
            {% if event|has:'thumbnail' %}
            <img src="{{ eventrun.event.thumbnail.url }}">
            {% else %}
            <div class="not-available"></div>
            {% endif %} 
        <div class='my-event-detail'>
        <p>EVENT: {{ event.name }}</p>
        <a href="{{ event.get_absolute_url }}">event detail </a>
        <a href="{% url 'events:edit_event' event.slug %}">edit event </a>
        <a href="{% url 'events:delete_event' event.slug %}">delete event </a>
        </div>
        {% endfor %}
    </div>
</div>
</div>
<div class="add-event-link">
<a class="add-event-link" href="{% url 'events:create_event' %}">ADD EVENT</a>
</div>
{% endblock content %}

explorea/templates/events/new_event_run.html
{% extends 'base.html' %} 

{% block title %}
<title>New Event Run</title>
{% endblock title %}

{% block content %}
<div class="basic-form-margin">

  <h2>Create new event run</h2>
  
  <form class="form-style" method="post">
    {% csrf_token %}
    {% for field in form.visible_fields %}
        {% for error in field.errors %}
        {{ error }}
        {% endfor %}

        <p>{{ field.label_tag}}{{ field }}</p>

    {% endfor %}
    <button type="submit">Save</button>
  </form>
  
</div>
{% endblock content %}